# SRT2Speech 默认配置文件
# 复制此文件为 config/local.yaml 来自定义您的设置

services:
  # GPT-SoVITS 本地TTS服务（推荐）
  gpt_sovits:
    service_name: gpt_sovits
    priority: 1  # 服务优先级（数字越小优先级越高）
    enabled: true
    
    credentials:
      api_url: "http://127.0.0.1:9880"  # GPT-SoVITS API地址
      api_version: "v2"  # API版本：v1 或 v2（推荐v2）
    
    # 自动启动设置（可选）
    auto_start:
      enabled: true  # 是否自动启动GPT-SoVITS服务
      gpt_sovits_path: "/Users/mingjun/Documents/Git Project/GPT-SoVITS"  # GPT-SoVITS项目路径，例如："/Users/mingjun/Documents/Git Project/GPT-SoVITS"
      startup_timeout: 30  # 启动超时时间（秒）
      use_command_script: false  # 对于API v2，建议设为false直接使用Python启动
    
    # 连接配置（可选）
    connection:
      host: "127.0.0.1"  # API监听地址
      port: 9880  # API监听端口
      timeout: 30  # 请求超时时间（秒）
      health_check_timeout: 5  # 健康检查超时时间（秒）
      max_retries: 3  # 最大重试次数
    
    # 重试策略（可选）
    retry_strategy:
      initial_delay: 1.0  # 初始重试延迟（秒）
      max_delay: 2.0  # 最大重试延迟（秒）
      connection_retry_delay: 2.0  # 连接失败重试延迟（秒）
    
    # 运行时配置（可选）
    runtime:
      python_path: "runtime/bin/python3"  # Python路径（相对于gpt_sovits_path）
      fallback_python: "python"  # 备用Python命令
      api_script_v1: "api.py"  # API v1脚本名
      api_script_v2: "api_v2.py"  # API v2脚本名
      config_file: "GPT_SoVITS/configs/tts_infer.yaml"  # 配置文件路径
      shutdown_wait: 0.5  # 关闭服务等待时间（秒）
    
    # 音频处理配置（可选）
    audio:
      silence_duration: 100  # 静音片段时长（毫秒）
    
    voice_settings:
      # 基础设置（必需）
      language: "auto"  # 语言：zh（中文）、en（英文）、ja（日文）、ko（韩文）、yue（粤语）、auto（多语种混合）
      
      # 参考音频配置 - 选择其中一种方式：
      
      # 方式1：使用预定义的音频配置（推荐）
      voice_profile: "default"  # 引用 config/reference_voices/default.yaml
      
      # 方式2：直接指定音频参数（会覆盖voice_profile）
      # ref_audio_path: "/path/to/your/reference.wav"
      # prompt_text: "参考音频的准确文本内容"
      # prompt_lang: "zh"
      
      # 提示：您可以在 config/reference_voices/ 目录下创建多个参考音频配置
      # 然后通过修改 voice_profile 来切换不同的声音
      
      # 采样参数（可选，影响生成质量）
      # 以下参数已优化以确保声音一致性
      top_k: 2  # Top-K采样，范围1-20，极低值确保最大稳定性
      top_p: 0.5  # Top-P采样，范围0-1，中低值减少变化
      temperature: 0.2  # 温度参数，范围0-2，极低温度确保声音一致
      
      # 生成控制（可选）
      speed_factor: 1.0  # 语速，范围0.5-2.0
      text_split_method: "cut5"  # 文本分割方法：cut0-cut5
      batch_size: 1  # 批处理大小
      batch_threshold: 0.75  # 批处理阈值
      split_bucket: true  # 是否分桶处理
      
      # 音频设置（可选）
      media_type: "wav"  # 输出格式：wav、ogg、aac
      streaming_mode: false  # 是否流式返回
      fragment_interval: 0.3  # 片段间隔（秒）
      
      # 高级参数（可选）
      seed: 2024  # 随机种子，固定值确保声音一致性（使用固定种子非常重要）
      parallel_infer: true  # 并行推理
      repetition_penalty: 1.2  # 重复惩罚，稍微降低增加自然度
      
      # V3版本专用参数（可选）
      sample_steps: 32  # 采样步数（仅V3版本）
      super_sampling: false  # 超采样（仅V3版本）

  # Google Gemini TTS服务
  gemini:
    service_name: gemini
    priority: 2  # 第二优先级（作为GPT-SoVITS的备选）
    enabled: true  # 启用Gemini服务（需要设置GEMINI_API_KEY环境变量）
    
    credentials:
      api_key: ""  # 可通过环境变量 GEMINI_API_KEY 设置
    
    voice_settings:
      # 模型选择
      model: "gemini-2.5-pro-preview-tts"  # 高质量TTS模型
      
      # 声音选择（30种可选）
      voice_name: "Kore"  # 默认声音，适合中文
      # 其他可选声音：Puck, Charon, Fenrir, Aoede, Vale, Journey 等
      
      # 语言设置
      language: "auto"  # 自动检测语言（适合中英文混合）

  # Azure Speech Services（预留）
  azure:
    service_name: azure
    priority: 3
    enabled: false
    credentials:
      # 设置 AZURE_SPEECH_KEY 和 AZURE_SPEECH_REGION 环境变量
      # 或在此指定
      subscription_key: ""
      region: "eastus"
    voice_settings:
      language: zh-CN
      gender: Female
      name: zh-CN-XiaoxiaoNeural
      speaking_rate: 1.0
      pitch: 0.0
      volume_gain_db: 0.0

# 输出设置
output:
  format: 'wav'
  sample_rate: 32000  # GPT-SoVITS默认输出32kHz
  channels: 1

# 音频处理设置
audio_processing:
  normalize: true
  remove_silence: false
  crossfade_duration: 0.01
  # 音频重叠处理策略
  overlap_handling: 'speed_adjust'  # 可选：'speed_adjust'（调速）、'truncate'（截断）、'warn_only'（仅警告）
  speed_adjust_limit: 2.0  # GPT-SoVITS 最大语速调整倍数
  max_total_speed: 4.0  # 总体最大加速倍数（GPT-SoVITS + 后处理）
  fade_duration: 0.05  # 截断时的淡出时长（秒）

# 缓存设置
cache:
  enabled: true
  directory: 'cache'
  max_size_mb: 1000

# 日志设置
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null

# 使用说明：
# 1. GPT-SoVITS服务启动方式：
#    
#    方式一：自动启动（推荐）
#    - 设置 auto_start.enabled: true
#    - 设置 auto_start.gpt_sovits_path 为您的GPT-SoVITS项目路径
#    - 运行srt2speech时会自动启动服务
#    
#    方式二：手动启动
#    - 保持 auto_start.enabled: false
#    - 手动启动服务：
#      cd /path/to/GPT-SoVITS
#      python api_v2.py -a 127.0.0.1 -p 9880
#
# 2. 准备参考音频：
#    - 建议使用3-10秒的清晰语音
#    - 确保音频质量良好，无背景噪音
#    - 文本要与音频内容完全匹配
#
# 3. 运行srt2speech：
#    python -m src.cli input.srt output.wav -c config/default.yaml